### ISSUE TITLE
grunt browser sync not injecting changes

### ISSUE THREAD

**Issue by Fabio-Ottaviani-Dev** [BrowserSync/recipes#11]
I tried grunt.html.injection example, but don't inject the Browsers when I modify the html / css files, the sync work properly only on Clicks and Scroll
![screen shot 2015-08-11 at 9 48 16 am](https://cloud.githubusercontent.com/assets/11891714/9203944/0205c57a-400f-11e5-8541-48600686e993.png)

**Comment by shakyShane** [comment]
@Fabio-Ottaviani-Dev Thanks for reporting this, it's fixed now in bs-recipes@1.2.2

:)
