### ISSUE TITLE
server includes cache issue

### ISSUE THREAD

**Issue by developer-prosenjit** [BrowserSync/recipes#18]
From this https://github.com/BrowserSync/recipes/tree/master/recipes/server.includes instruction I successfully setup server includes but when I change template auto reload working but not update the template content.

**Comment by shakyShane** [comment]
@developer-prosenjit this is likely a browser-cache issue, could disable cache and see if it works?

**Comment by developer-prosenjit** [comment]
Yes it's works. Thanks.
