### ISSUE TITLE
webpack.react-transform-hmr recipe doesn't generate bundle.js

### ISSUE THREAD

**Issue by vvatikiotis** [BrowserSync/recipes#19]
Hello,

I'm testing webpack.react-transform-hmr and I noticed that it doesn't generate bundle.js in any directory. How can I achieve this?

**Comment by LostKobrakai** [comment]
Hot module replacement does not generate files in the file system. It's holding the files in memory and serves them from there.

**Comment by vvatikiotis** [comment]
Thanks @LostKobrakai, obvious, however I missed it.
