### ISSUE TITLE
Question: support for hot-reloading JS?

### ISSUE THREAD

**Issue by rstacruz** [BrowserSync/recipes#20]
When changing CSS files, they're changed without reloading the page. Would it be possible to do the same for JavaScript files (and leave it to the user to figure out how to implement it in their code)?

**Comment by rstacruz** [comment]
uh oh... filed in the wrong repo.

**Comment by tony19** [comment]
@rstacruz Where did you end up asking the question?

**Comment by rstacruz** [comment]
https://github.com/BrowserSync/browser-sync
