### ISSUE TITLE
Gulp and SASS recipes not working

### ISSUE THREAD

**Issue by MiLeung** [BrowserSync/recipes#22]
Michaels-MBP-4:gulp.jade MichaelLeung$ npm start

> gulp.jade@1.0.0 start /Users/MichaelLeung/bs-recipes/recipes/gulp.jade
> gulp

/Users/MichaelLeung/bs-recipes/recipes/gulp.jade/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/MichaelLeung/bs-recipes/recipes/gulp.jade/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/MichaelLeung/bs-recipes/recipes/gulp.jade/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/MichaelLeung/bs-recipes/recipes/gulp.jade/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:435:26)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! gulp.jade@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulp.jade@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gulp.jade package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gulp.jade
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gulp.jade
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MichaelLeung/bs-recipes/recipes/gulp.jade/npm-debug.log

I followed the instructions like the ones [here](https://github.com/Browsersync/recipes/tree/master/recipes/gulp.sass) and got the following message above after running npm start.

**Comment by michaellashinsky** [comment]
the gulp.sass along with the gulp.jade both fail with the same node-sass error.

**Comment by kartiklad** [comment]
@michaellashinsky I think you might be using node 4.0 or higher. Upgrade the gulp-sass plugin to 2.2.0 and it should be fine

**Comment by shakyShane** [comment]
Fixed in bs-recipes@1.2.1

**Comment by shakyShane** [comment]
Thanks @MiLeung for reporting the issue
