### ISSUE TITLE
Can BrowserSync be configured via the API using a bs-config.json file?

### ISSUE THREAD

**Issue by autopulous** [BrowserSync/recipes#26]
I would like to start browser-sync via Gulp using the configuration specified in my bs-config.json file - this does not seem to work for me even though my bs-config.json is in the same directory as my gulpfile.js. My thought was that the .init() function might be able to accept a path to the bs-config.json file, but I cannot find a reference regarding if this is possible in the the BrowserSync documentation...

Is this possible? or is there a better way to accomplish what I'm trying to do?

**Comment by shakyShane** [comment]
Sure, just require the file.

bs.init(require('./bs-config'))
