### ISSUE TITLE
server.gzipped.assets Recipe Not Picking Up .html Files

### ISSUE THREAD

**Issue by realph** [BrowserSync/recipes#4]
I can't seem to get the [server.gzipped.assets Recipe](https://github.com/Browsersync/recipes/tree/master/recipes/server.gzipped.assets) to pick up my `.html.gz` files. Gulp task looks like this:

    gulp.task('serve', function () {
      browserSync({
        server: "./_site",
        files: ['./_site/public/css/*.css', './_site/public/js/*.js', './_site/*.html', './_site/**/*.html'],
        middleware: require("connect-gzip-static")("./_site")
      });
    });

Any help is appreciated. Thanks in advance!

**Comment by shinnn** [comment]
```js
gulp.task('serve', function () {
  browserSync({
    server: "./_site",
    files: ['./_site/public/css/*.css', './_site/public/js/*.js', './_site/**/*.html{,.gz}'],
    middleware: require("connect-gzip-static")("./_site")
  });
});
```

**Comment by realph** [comment]
@shinnn I've used the above code, but Chrome is still picking up my 67KB file rather than my 28KB `.gz` file.

![screen shot 2015-06-01 at 13 18 37](https://cloud.githubusercontent.com/assets/2334951/7912588/c041cd9a-0860-11e5-9b20-5fc38d59a59a.png)
![screen shot 2015-06-01 at 13 18 19](https://cloud.githubusercontent.com/assets/2334951/7912591/c1a00f30-0860-11e5-9165-ec0bf2db68a3.png)

**Comment by shinnn** [comment]
@realph I thought "pick up my `.html.gz` files" means "BrowserSync watches my `.html.gz` files". What do you mean by "pick up"?

**Comment by realph** [comment]
@shinnn I want BrowserSync to serve my `.html.gz` files to Chrome, so Chrome renders the compressed html files.

**Comment by shinnn** [comment]
@realph OK, thanks. I have no experience in serving gzipped files with Browsersync, so I'd like to leave this issue to @shakyShane.

**Comment by realph** [comment]
@shinnn Thanks for your help. @shakyShane ...?

**Comment by shakyShane** [comment]
@realph the problem here is that the middleware is too late in the stack when added via the options for .html files (as serve-static) ends the request prematurely thinking that the index file doesn't exist.

The following will work perfectly though because `override` will put your middleware at the front of the stack.

```js
gulp.task('serve', function () {
    browserSync({
        server: "./_site",
        files: ['./_site/public/css/*.css', './_site/public/js/*.js', './_site/*.html', './_site/**/*.html']
    }, function (err, bs) {
        bs.addMiddleware("*", require('connect-gzip-static')('./_site'), {
            override: true
        });
    });
});
```

**Comment by shakyShane** [comment]
Updated the recipe to reflect this

**Comment by realph** [comment]
Thanks for this @shakyShane! Works perfectly now.

**Comment by shakyShane** [comment]
![tumblr_m0osrrhqmk1qzcv7no4_250](https://cloud.githubusercontent.com/assets/1643522/7914348/5370819e-086e-11e5-93f7-4367abec3b18.gif)

**Comment by realph** [comment]
@shakyShane Sorry to nag. I've just realised that I don't know how to add back my BrowserSync reload. I'm calling BrowserSync's reload at the end of my tasks like so:

    .pipe(reload({stream: true}))

Any idea what I've got to do to get it back?

**Comment by shakyShane** [comment]
Can you show us your gulpfile and explain what you expect to happen :)

**Comment by realph** [comment]
@shakyShane 

My `gulpfile.js` looks like this:

    var gulp = require('gulp');

    var browserSync = require('browser-sync');
    var browserSyncCreate = browserSync.create();
    var middleware = require('connect-gzip-static')('./_site');
    var reload = browserSync.reload;

    // Start server
    gulp.task('serve', function () {
      browserSyncCreate.init({
        server: './_site',
        files: [
          './_site/**/*.html',
          './_site/public/css/*.css',
          './_site/public/js/*.js'
        ],
      }, function (err, bs) {
          bs.addMiddleware("*", middleware, {
            override: true
         });
      });
    });

    // Jekyll task
    gulp.task('jekyll', function() {
      return gulp.src('./index.html')
        .pipe(shell(['jekyll build']))
        .pipe(reload({stream: true}))
    });

    // Default task
    gulp.task('default', ['jekyll'], function() {
      gulp.watch(['./index.html', './*.md', '_includes/**/*.html', '_layouts/**/*.html', 'posts/*.html', '_posts/**/*'], ['jekyll']);
    });

When changes are made to the watch directory in the `default` task, I want to run my `jekyll` task, at the end of the `jekyll` task, you'll see I'm using `.pipe(reload({stream: true}))`. I want BrowserSync to reload my browser when a change is detected.

Ever since I changed the server task to `browserSyncCreate.init()` the reloads haven't worked the same, I was previously using simply `browserSync()` for my my server task, and reloads worked.

Hope that explains it. Thanks!

**Comment by shakyShane** [comment]
You can use `.stream()` for that

```js
var gulp = require('gulp');

var browserSync = require('browser-sync').create();
var middleware = require('connect-gzip-static')('./_site');

// Start server
gulp.task('serve', function () {
    browserSync.init({
        server: './_site',
        files: [
            './_site/**/*.html',
            './_site/public/css/*.css',
            './_site/public/js/*.js'
        ],
    }, function (err, bs) {
        bs.addMiddleware("*", middleware, {
            override: true
        });
    });
});

// Jekyll task
gulp.task('jekyll', function() {
    return gulp.src('./index.html')
        .pipe(shell(['jekyll build']))
        .pipe(browserSync.stream())
});

// Default task
gulp.task('default', ['jekyll'], function() {
    gulp.watch(['./index.html', './*.md', '_includes/**/*.html', '_layouts/**/*.html', 'posts/*.html', '_posts/**/*'], ['jekyll']);
});
```

**Comment by shakyShane** [comment]
or try this, (which i prefer, as is keeps Browsersync related stuff out of the jekyll task

```js
var gulp = require('gulp');

var browserSync = require('browser-sync').create();
var middleware = require('connect-gzip-static')('./_site');

// Start server
gulp.task('serve', function () {
    browserSync.init({
        server: './_site',
        files: [
            './_site/**/*.html',
            './_site/public/css/*.css',
            './_site/public/js/*.js'
        ],
    }, function (err, bs) {
        bs.addMiddleware("*", middleware, {
            override: true
        });
    });
});

// Jekyll + reload
gulp.task('jekyll-reload', ['jekyll'], browserSync.reload);

// Jekyll task
gulp.task('jekyll', function() {
    return gulp.src('./index.html')
        .pipe(shell(['jekyll build']));
});

// Default task
gulp.task('default', ['jekyll'], function() {
    gulp.watch(['./index.html', './*.md', '_includes/**/*.html', '_layouts/**/*.html', 'posts/*.html', '_posts/**/*'], ['jekyll-reload']);
});
```

**Comment by shakyShane** [comment]
^ note that I call `jekyll-reload` in the watch task there

**Comment by realph** [comment]
@shakyShane I'll give these a try. Any reason why you like to keep BrowserSync away from main task and its own separate task? Do you also do this for Sass, JS tasks?

**Comment by shakyShane** [comment]
because, sometimes you only want to run `gulp jekyll` or a similar command without the whole watching/reloading setup. In this context, whilst it will still work, it doesn't make sense to pipe anything to Browsersync.

**Comment by realph** [comment]
@shakyShane I'm using your second example, but BrowserSync doesn't seem to be running the `.reload` meth. Manual reload works just fine.

**Comment by schiz** [comment]
@realph did you succeed? can you paste the code, how did you manage to do it? I use the same stack - and found out that only when using connect-gzip-static reload doesn't work. None of fixes listed above didn't work for me.

**Comment by johnpapa** [comment]
@shakyShane How would i serve gzip files when I am using the config file instead of gulp?

```
      middleware: [
        require('connect-gzip-static')('./dist'), {override: true }
      ]
```

does not seem to work like this ...

**Comment by shakyShane** [comment]
@johnpapa 2 solutions.

On recent versions of BS, (2.15 + I think), you can provide an object as a middleware definition and use `override` there

```js
modules.exports = {
    server: './app',
    middleware: [
        {
            route: "", // empty 'route' will apply this to all paths
            handle: require('connect-gzip-static')('./app'), // the callable
            override: true
        }
    ]
};
```

As mentioned above, the `override` boolean will cause this middleware to be applied to the FRONT of the stack.

Alternatively, when using the configuration file, you can still get hold of the running instance through `callbacks`

```js
const middleware = require('connect-gzip-static')('./app');

modules.exports = {
    server: './app',
    callbacks: {
        ready: function (err, bs) {
            // access bs methods as normal
            bs.addMiddleware("*", middleware, {
                override: true
            });
        }
    }
};
```

Hope that helps :)

**Comment by shakyShane** [comment]
@johnpapa assuming your files are already gripped of course! to gzip on the fly look at 'compression' module
