### ISSUE TITLE
Recipes With Updated Dependencies?

### ISSUE THREAD

**Issue by peterkrieg** [BrowserSync/recipes#40]
Hello,

First of all, these were super helpful, so thanks for putting together!  For my personal project however, I had to use some later versions of dependencies (react, babel, etc) which had some breaking changes.

Is there interest in updating the recipes to work with newer versions of deps? If so, I could make a pull request with bare minimum changes for bumping versions.

**Comment by shakyShane** [comment]
Yes please, that sounds great!

**Comment by peterkrieg** [comment]
Okay @shakyShane, just submitted a PR - let me know what you think!  Just updated 2 recipes for now (only ones relevant to what I was working on) but could consider looking at others as well.

**Comment by soluml** [comment]
We've been trying to get the webpack react hot loader recipe working with Webpack 2. Any chance you have a working recipe with that @peterkrieg?  A guy can hope :)

**Comment by peterkrieg** [comment]
@soluml  - no, I'm afraid I haven't used webpack 2 yet.  I've heard it's difficult getting the two to play nicely though.. best of luck :)

**Comment by shakyShane** [comment]
available in browser-sync@2.18.6
