### ISSUE TITLE
Is it possible to just use BrowserSync for CSS with a site that is already live?

### ISSUE THREAD

**Issue by BMOv2600** [BrowserSync/recipes#9]
I've gotten BrowserSync working to the point where it tells me that it has injected CSS, but not to the point where it actually does. I tried the HTML/CSS injection example to get it working, but it seems like it and all the recipes involve script task runners, Sass, or both.

Is there any way to use BrowserSync just to watch a stylesheet with CLI? Or does using BrowserSync effectively also require a pretty thorough understanding of javascript task runners, CSS preprocessors, or both?

**Comment by shakyShane** [comment]
say you have index.html

```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css"/>
</head>
<body>
    <h1>MY website</h1>
</body>
</html>
```

and a css `css/style.css`

```css
body { background: red; }
```

in the same directory at the `index.html`, run 

```shell
browser-sync start --server --files="*.html,css/*.css"
```

**Comment by BMOv2600** [comment]
Thank you.
